package com.blogging_platform.model;

import java.sql.Types;
import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Domain model for a comment on a post. Use {@link #forCreate(String, String, String)} for new comments
 * and {@link #forEdit(String, String, String)} for updates.
 */
@Entity
@Table(name = "comments")
public class Comment {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(Types.BINARY)
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Comment identifier, generated by the system")
    private UUID id;

    @NotNull(message = "User id is required")
    @Schema(description = "Identifier of the user creating the comment")
    @JdbcTypeCode(Types.BINARY)
    @Column(name = "user_id")
    private UUID userId;

    @NotNull(message = "Post id is required")
    @Schema(description = "Identifier of the post being commented on")
    @JdbcTypeCode(Types.BINARY)
    @Column(name = "post_id")
    private UUID postId;

    /**
     * Owning user of the comment. JPA relation; {@link #userId} exposes FK as scalar.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private User user;

    /**
     * Post this comment belongs to. JPA relation; {@link #postId} exposes FK as scalar.
     */
    @ManyToOne
    @JoinColumn(name = "post_id", insertable = false, updatable = false)
    private Post post;

    @NotBlank(message = "Comment is required")
    @Schema(description = "Comment text")
    private String comment;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Additional metadata set by the system")
    private String metadata;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the comment was created")
    private LocalDateTime datetime;

    
    private Comment() {
    }

    /**
     * Creates a comment instance for editing an existing comment.
     *
     * @param id      comment id
     * @param userId  user id
     * @param comment new content
     * @return a Comment instance for update
     */
    public static Comment forEdit(String id, String userId, String comment) {
        Comment c = new Comment();
        c.id = id != null ? UUID.fromString(id) : null;
        c.userId = userId != null ? UUID.fromString(userId) : null;
        c.comment = comment;
        return c;
    }

    /**
     * Creates a comment instance for adding a new comment to a post.
     *
     * @param comment comment text
     * @param userId  user id
     * @param postId  post id
     * @return a Comment instance for create
     */
    public static Comment forCreate(String comment, String userId, String postId) {
        Comment c = new Comment();
        c.comment = comment;
        c.userId = userId != null ? UUID.fromString(userId) : null;
        c.postId = postId != null ? UUID.fromString(postId) : null;
        return c;
    }
    public UUID getId() {
        return id;
    }
    public void setId(UUID id) {
        this.id = id;
    }
    public UUID getUserId() {
        return userId;
    }
    public void setUserId(UUID userId) {
        this.userId = userId;
    }
    public UUID getPostId() {
        return postId;
    }
    public void setPostId(UUID postId) {
        this.postId = postId;
    }
    public String getComment() {
        return comment;
    }
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getMetadata() {
        return metadata;
    }
    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }
    public LocalDateTime getDatetime() {
        return datetime;
    }
    public void setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
        if (user != null) {
            this.userId = user.getId();
        }
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
        if (post != null) {
            this.postId = post.getId();
        }
    }

}
