package com.blogging_platform.model;

import java.sql.Types;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.validation.constraints.NotBlank;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Domain model for a blog post. Used when creating or updating posts via the service layer.
 * Mapped as a JPA entity with relations to {@link User} and {@link Tag}.
 */
@Entity
@Table(name = "posts")
public class Post {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(Types.BINARY)
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Post identifier, generated by the system")
    private UUID id;
    
    @Schema(description = "Identifier of the user who owns the post")
    @JdbcTypeCode(Types.BINARY)
    @Column(name = "user_id")
    private UUID userId;

    /**
     * Owning user of the post. This is the JPA relation; {@link #userId} exposes the FK as a scalar.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private User user;

    @NotBlank(message = "Title is required")
    @Schema(description = "Post title")
    private String title;

    @NotBlank(message = "Content is required")
    @Schema(description = "Post content/body")
    private String content;

    @NotBlank(message = "Post status is required")
    @Schema(description = "Post status, e.g. PUBLISH/DRAFT")
    private String status;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the post was created")
    private LocalDateTime createdAt;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the post was published")
    private LocalDateTime publishedDatetime;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Whether the post is currently published")
    @Transient
    private boolean isPublish;

    /**
     * Tags associated with this post (many-to-many via post_tags join table).
     */
    @ManyToMany
    @JoinTable(
        name = "post_tags",
        joinColumns = @JoinColumn(name = "post_id"),
        inverseJoinColumns = @JoinColumn(name = "tag_id")
    )
    private Set<Tag> tags = new HashSet<>();

    public Post(){}

    public Post(UUID userId, String title, String content, String status) {
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.status = status;
    }

    public Post(UUID postId, UUID userId, String title, String content, String status) {
        this.id = postId;
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.status = status;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
        if (user != null) {
            this.userId = user.getId();
        }
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getPublishedDatetime() {
        return publishedDatetime;
    }

    public void setPublishedDatetime(LocalDateTime publishedDatetime) {
        this.publishedDatetime = publishedDatetime;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setIsPublish(boolean b) {
        this.isPublish = b;
    }

    public boolean getIsPublish(){
        return this.isPublish;
    }

    public Set<Tag> getTags() {
        return tags;
    }

    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }
}
