package com.blogging_platform.model;

import java.time.LocalDateTime;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Domain model for a blog post. Used when creating or updating posts via the service layer.
 */
@Entity
public class Post {
    @Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Post identifier, generated by the system")
    private String id;
    
    @NotBlank(message = "User id is required")
    @Schema(description = "Identifier of the user who owns the post")
    private String userId;

    @NotBlank(message = "Title is required")
    @Schema(description = "Post title")
    private String title;

    @NotBlank(message = "Content is required")
    @Schema(description = "Post content/body")
    private String content;

    @NotBlank(message = "Post status is required")
    @Schema(description = "Post status, e.g. PUBLISH/DRAFT")
    private String status;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the post was created")
    private LocalDateTime createdAt;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the post was published")
    private LocalDateTime publishedDatetime;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Whether the post is currently published")
    private boolean isPublish;

    public Post(){}

    public Post(String userId, String title, String content, String status) {
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.status = status;
    }

    public Post(String postId, String userId, String title, String content, String status) {
        this.id = postId;
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.status = status;
    }

    

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getPublishedDatetime() {
        return publishedDatetime;
    }

    public void setPublishedDatetime(LocalDateTime publishedDatetime) {
        this.publishedDatetime = publishedDatetime;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setIsPublish(boolean b) {
        this.isPublish = b;
    }

    public boolean getIsPublish(){
        return this.isPublish;
    }
}
