package com.blogging_platform.model;

import java.sql.Types;
import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Domain model for a post review (rating 1–5 and message). Used when creating
 * or updating reviews.
 */
@Entity
@Table(name = "reviews")
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(Types.BINARY)
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Review identifier, generated by the system")
    private UUID id;

    @Schema(description = "Identifier of the post being reviewed")
    @JdbcTypeCode(Types.BINARY)
    @Column(name = "post_id")
    private UUID postId;

    @Schema(description = "Identifier of the user writing the review")
    @JdbcTypeCode(Types.BINARY)
    @Column(name = "user_id")
    private UUID userId;

    /**
     * Post that this review belongs to. JPA relation; {@link #postId} exposes FK as
     * scalar.
     */
    @ManyToOne
    @JoinColumn(name = "post_id", insertable = false, updatable = false)
    private Post post;

    /**
     * User who wrote this review. JPA relation; {@link #userId} exposes FK as
     * scalar.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private User user;

    @NotNull(message = "Rating is required")
    @Min(value = 1, message = "Rating must be at least 1")
    @Max(value = 5, message = "Rating cannot be more than 5")
    @Schema(description = "Rating value between 1 and 5")
    private Integer rating;

    @NotBlank(message = "Review message is required")
    @Schema(description = "Review text")
    private String message;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Timestamp when the review was created")
    private LocalDateTime createdAt;

    public Review() {
    }

    public Review(UUID postId, UUID userId, Integer rating, String message) {
        this.postId = postId;
        this.userId = userId;
        this.rating = rating;
        this.message = message;
    }

    public Review(String id, UUID postId, UUID userId, Integer rating, String message) {
        this.id = id != null ? UUID.fromString(id) : null;
        this.postId = postId;
        this.userId = userId;
        this.rating = rating;
        this.message = message;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getPostId() {
        return postId;
    }

    public void setPostId(UUID postId) {
        this.postId = postId;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
        if (post != null) {
            this.postId = post.getId();
        }
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
        if (user != null) {
            this.userId = user.getId();
        }
    }
}
