package com.blogging_platform.model;


import java.sql.Types;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;

import com.blogging_platform.validation.UniqueEmail;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Domain model for a user (registration, login). Holds name, email, password, and role.
 */
@Entity
@Table(name = "users")
public class User {
    @Id
    @JdbcTypeCode(Types.BINARY)
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "User identifier, generated by the system")
    private UUID id;

    @NotBlank(message = "Name is required")
    @Schema(description = "Full name of the user")
    private String name;
    
    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    @UniqueEmail
    @Schema(description = "Unique email address of the user")
    private String email;
    
    @NotBlank(message = "Password is required")
    @Size(min = 8, message = "Password must be at least 8 characters")
    @Schema(description = "User password (write-only in API)", accessMode = Schema.AccessMode.WRITE_ONLY)
    private String password;

    @NotBlank(message = "Role is required")
    @Schema(description = "User role (e.g. ADMIN, USER)")
    private String role;

    public User(){}

    
    public User(String name, String email, String password, String role) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    public UUID getId() {
        return id;
    }
    public void setId(UUID id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return role;
    }
    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", name=" + name + ", email=" + email + ", password=" + password + ", role=" + role
                + "]";
    }
}
